app_url: https://medsum-admin.carasent.dev

image:
  repository: harbor.dev.carasent-ck8s.com/medsum/medsum-admin
  pullPolicy: IfNotPresent
  tag: ""

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: "52.149.120.222,95.111.208.41/32"
  hosts:
    - host: medsum-admin.carasent.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: medsum-admin.carasent.dev-tls
      hosts:
        - medsum-admin.carasent.dev
