services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_STAGE:-development}
    networks:
      - postgres-network
      - medsum-net
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - S3_REGION=us-east-1
      - S3_ENDPOINT=http://localstack:4566
      - S3_ACCESS_KEY_ID=test
      - S3_SECRET_ACCESS_KEY=test
    env_file:
      - .env
    volumes:
      - .:/app
    command: "npm run dev"
    depends_on:
      - database
      - localstack
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=medsum
      - POSTGRES_PASSWORD=medsum
      - POSTGRES_DB=medsum
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
    ports:
      - 5432:5432

  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3
      - DEBUG=1
    networks:
      - medsum-net
    volumes:
      - localstack-data:/var/lib/localstack

volumes:
  postgres-data:
  localstack-data:

networks:
  postgres-network:
  medsum-net:
    name: medsum
    external: true
